// ===========================================================================
// Import export all icons here in a uniform format for better autocomplete.
// - 🌳 They are Tree-shaked by Vite.
// - Custom icons (.svg) can be added in this folder and exported thanks to vite-plugin-solid-svg.
// - Get your icons from https://icones.js.org/
// =========================================================================';

export { default as IconAnthropic } from "./anthropic"
export { default as IconCopy } from "./copy"
export { default as IconGitHub } from "./devicon:github.svg"
export { default as IconGoogle } from "./devicon:google.svg"
export { default as IconGemini } from "./gemini"
export { default as IconLoading } from "./line-md:loading-twotone-loop.svg"
export { default as IconArrowDown } from "./lucide:arrow-down.svg"
export { default as IconArrowUp } from "./lucide:arrow-up.svg"
export { default as IconCheck } from "./lucide:check.svg"
export { default as IconChevronsUpDown } from "./lucide:chevrons-up-down.svg"
export { default as IconDotsVertical } from "./lucide:ellipsis-vertical.svg"
export { default as IconEye } from "./lucide:eye.svg"
export { default as IconEyeOff } from "./lucide:eye-off.svg"
export { default as IconMoon } from "./lucide:moon.svg"
export { default as IconPlus } from "./lucide:plus.svg"
export { default as IconSun } from "./lucide:sun.svg"
export { default as IconUpload } from "./lucide:upload.svg"
export { default as IconArrowUpRight } from "./lucide_arrow-up-right.svg"
export { default as IconBook } from "./lucide_book.svg"
export { default as IconChevronDown } from "./lucide_chevron-down.svg"
export { default as IconChevronLeft } from "./lucide_chevron-left.svg"
export { default as IconChevronRight } from "./lucide_chevron-right.svg"
export { default as IconChevronUp } from "./lucide_chevron-up.svg"
export { default as IconChevronsLeft } from "./lucide_chevrons-left.svg"
export { default as IconChevronsRight } from "./lucide_chevrons-right.svg"
export { default as IconCirclePlus } from "./lucide_circle-plus.svg"
export { default as IconCode } from "./lucide_code.svg"
export { default as IconFile } from "./lucide_file.svg"
export { default as IconFolder } from "./lucide_folder.svg"
export { default as IconHash } from "./lucide_hash.svg"
export { default as IconLink } from "./lucide_link.svg"
export { default as IconPackage } from "./lucide_package.svg"
export { default as IconRocket } from "./lucide_rocket.svg"
export { default as IconSettings } from "./lucide_settings.svg"
export { default as IconSquareTerminal } from "./lucide_square-terminal.svg"
export { default as IconMarkdownLine } from "./markdown-line"
export { default as IconX } from "./material-symbols:close-small-rounded.svg"
export { default as IconMenu } from "./mdi:menu"
export { default as IconOpenAI } from "./openai"
export { default as IconFileCss } from "./simple-icons_css.svg"
export { default as IconFileDocker } from "./simple-icons_docker.svg"
export { default as IconFileGo } from "./simple-icons_go.svg"
export { default as IconFileHtml } from "./simple-icons_html5.svg"
export { default as IconFileJs } from "./simple-icons_javascript.svg"
export { default as IconFileJson } from "./simple-icons_json.svg"
export { default as IconFileMarkdown } from "./simple-icons_markdown.svg"
export { default as IconFilePython } from "./simple-icons_python.svg"
export { default as IconFileReact } from "./simple-icons_react.svg"
export { default as IconFileRust } from "./simple-icons_rust.svg"
export { default as IconFileTypescript } from "./simple-icons_typescript.svg"
export { default as IconFileYaml } from "./simple-icons_yaml.svg"
export { default as IconSolid } from "./solid.svg"
export { default as IconAlertFilled } from "./tabler:alert-triangle-filled.svg"
export { default as IconFileGeneric } from "./tabler_file.svg"
export { default as IconFileCode } from "./tabler_file-code.svg"
export { default as IconFileConfig } from "./tabler_file-settings.svg"
export { default as IconFileText } from "./tabler_file-text.svg"
export { default as IconFolderTree } from "./tabler_folder.svg"
export { default as IconFileImage } from "./tabler_photo.svg"
export { default as IconFileShell } from "./tabler_terminal-2.svg"
