// This file is generated by prepare-docs.ts

import type { DocsConfig, GitHubRepo, NavItem } from "@/gittydocs/lib/config-schema"

export type { DocsConfig, GitHubRepo, NavItem }

export const gittydocsConfig: DocsConfig | null = {
  "nav": [
    {
      "label": "Docs",
      "items": [
        {
          "label": "Introduction",
          "path": "/introduction",
          "icon": "book"
        },
        {
          "label": "Motivation",
          "path": "/motivation",
          "icon": "rocket"
        },
        {
          "label": "AI Docs Prompt",
          "path": "/ai-docs-prompt",
          "icon": "file"
        },
        {
          "label": "Configuration",
          "path": "/configuration",
          "icon": "settings"
        },
        {
          "label": "Navigation",
          "path": "/navigation",
          "icon": "folder"
        },
        {
          "label": "CLI",
          "path": "/cli",
          "icon": "terminal"
        },
        {
          "label": "Theming",
          "path": "/theming",
          "icon": "settings"
        }
      ],
      "icon": "book"
    },
    {
      "label": "Components",
      "path": "/components",
      "items": [
        {
          "label": "Code blocks",
          "path": "/components/code-blocks",
          "icon": "code"
        },
        {
          "label": "Authoring",
          "items": [
            {
              "label": "Steps",
              "path": "/components/steps",
              "icon": "hash"
            },
            {
              "label": "Files",
              "path": "/components/files",
              "icon": "folder"
            },
            {
              "label": "Accordion",
              "path": "/components/accordion",
              "icon": "file"
            }
          ],
          "accordion": true,
          "icon": "book",
          "defaultOpen": true
        }
      ],
      "icon": "package"
    },
    {
      "label": "Deploy",
      "items": [
        {
          "label": "Overview",
          "path": "/deploy"
        },
        {
          "label": "GitHub Pages",
          "path": "/deploy/github-pages"
        },
        {
          "label": "Vercel",
          "path": "/deploy/vercel"
        },
        {
          "label": "Cloudflare Pages",
          "path": "/deploy/cloudflare"
        },
        {
          "label": "Netlify",
          "path": "/deploy/netlify"
        }
      ],
      "accordion": true,
      "icon": "rocket"
    }
  ],
  "navFooter": [
    {
      "label": "GitHub",
      "path": "https://github.com/blankeos/gittydocs",
      "icon": "github"
    }
  ],
  "links": {
    "github": "https://github.com/blankeos/gittydocs",
    "issues": "https://github.com/blankeos/gittydocs/issues"
  },
  "theme": {
    "preset": "ocean"
  },
  "site": {
    "name": "gittydocs",
    "version": "0.0.5",
    "description": "Simple, fast docs from your Markdown.",
    "logo": "/static/gittydocs_logo.png",
    "favicon": "/static/gittydocs_logo.png",
    "socialBanner": "/static/gittydocs_mainbanner.jpg",
    "repo": {
      "owner": "blankeos",
      "name": "gittydocs",
      "ref": "main",
      "docsPath": "docs"
    }
  }
}
