// This file is generated by prepare-docs.ts

import type { DocsConfig, GitHubRepo, NavItem } from "@/gittydocs/lib/config-schema"

export type { DocsConfig, GitHubRepo, NavItem }

export const gittydocsConfig: DocsConfig | null = {
  "site": {
    "name": "gittydocs",
    "description": "Simple, fast docs from your Markdown.",
    "logo": "/static/gittydocs_logo.png",
    "favicon": "/static/gittydocs_logo.png",
    "socialBanner": "/static/gittydocs_mainbanner.jpg",
    "repo": {
      "owner": "blankeos",
      "name": "gittydocs",
      "ref": "main",
      "docsPath": "docs"
    }
  },
  "nav": [
    {
      "label": "Docs",
      "items": [
        {
          "label": "Introduction",
          "path": "/"
        },
        {
          "label": "Motivation",
          "path": "/motivation"
        },
        {
          "label": "AI Docs Prompt",
          "path": "/ai-docs-prompt"
        },
        {
          "label": "Configuration",
          "path": "/configuration"
        },
        {
          "label": "CLI",
          "path": "/cli"
        },
        {
          "label": "Theming",
          "path": "/theming"
        }
      ]
    },
    {
      "label": "Deploy",
      "items": [
        {
          "label": "Overview",
          "path": "/deploy"
        },
        {
          "label": "GitHub Pages",
          "path": "/deploy/github-pages"
        },
        {
          "label": "Vercel",
          "path": "/deploy/vercel"
        },
        {
          "label": "Cloudflare Pages",
          "path": "/deploy/cloudflare"
        },
        {
          "label": "Netlify",
          "path": "/deploy/netlify"
        }
      ],
      "accordion": true
    }
  ],
  "links": {
    "github": "https://github.com/blankeos/gittydocs",
    "issues": "https://github.com/blankeos/gittydocs/issues"
  },
  "theme": {
    "preset": "ocean"
  }
}
