// This file is generated by prepare-docs.ts

export interface GitHubRepo {
  owner: string
  repo: string
  ref: string
  docsPath: string
}

export interface NavItem {
  label: string
  path?: string
  items?: NavItem[]
  accordion?: boolean
}

export interface DocsConfig {
  site: {
    name: string
    description?: string
    logo?: string
    repo?: GitHubRepo
  }
  nav?: NavItem[]
  links?: {
    github?: string
    issues?: string
  }
  theme?: {
    preset?: string
    cssFile?: string
  }
  llms?: {
    enabled?: boolean
    path?: string
  }
}

export const gittydocsConfig: DocsConfig | null = {
  "site": {
    "name": "gittydocs",
    "description": "Simple, fast docs from your Markdown.",
    "logo": "/icon-logo.svg",
    "repo": {
      "owner": "blankeos",
      "name": "gittydocs",
      "ref": "main",
      "docsPath": "docs"
    }
  },
  "theme": {
    "preset": "ocean"
  },
  "nav": [
    {
      "label": "Docs",
      "items": [
        {
          "label": "Introduction",
          "path": "/"
        },
        {
          "label": "Motivation",
          "path": "/motivation"
        },
        {
          "label": "AI Docs Prompt",
          "path": "/ai-docs-prompt"
        },
        {
          "label": "Configuration",
          "path": "/configuration"
        },
        {
          "label": "CLI",
          "path": "/cli"
        },
        {
          "label": "Theming",
          "path": "/theming"
        }
      ]
    },
    {
      "label": "Deploy",
      "accordion": true,
      "items": [
        {
          "label": "GitHub Pages",
          "path": "/deploy/github-pages"
        },
        {
          "label": "Vercel",
          "path": "/deploy/vercel"
        },
        {
          "label": "Cloudflare Pages",
          "path": "/deploy/cloudflare"
        },
        {
          "label": "Netlify",
          "path": "/deploy/netlify"
        }
      ]
    }
  ],
  "links": {
    "github": "https://github.com/blankeos/gittydocs",
    "issues": "https://github.com/blankeos/gittydocs/issues"
  }
}
