export const sourcePathByRoute: Record<string, string> = {
  "/": "index.tsx",
  "/configuration": "configuration.mdx",
  "/motivation": "motivation.mdx",
  "/cli": "cli.mdx",
  "/deploy/cloudflare": "deploy/cloudflare.mdx",
  "/deploy/github-pages": "deploy/github-pages.mdx",
  "/deploy/netlify": "deploy/netlify.mdx",
  "/deploy": "deploy/index.mdx",
  "/deploy/vercel": "deploy/vercel.mdx",
  "/ai-docs-prompt": "ai-docs-prompt.mdx",
  "/navigation": "navigation.mdx",
  "/introduction": "introduction.mdx",
  "/components/code-blocks": "components/code-blocks.mdx",
  "/components/files": "components/files.mdx",
  "/components/accordion": "components/accordion.mdx",
  "/components": "components/index.mdx",
  "/components/steps": "components/steps.mdx",
  "/theming": "theming.mdx"
}
