// This file is generated by prepare-docs.ts

export interface GitHubRepo {
  owner: string
  repo: string
  ref: string
  docsPath: string
}

export interface NavItem {
  label: string
  path?: string
  items?: NavItem[]
}

export interface DocsConfig {
  site: {
    name: string
    logo?: string
    repo?: GitHubRepo
  }
  nav?: NavItem[]
  links?: {
    issues?: string
  }
}

export const gittydocsConfig: DocsConfig | null = {
  "site": {
    "name": "Coffee Brewing Guide",
    "repo": {
      "owner": "anomalyco",
      "name": "gittydocs",
      "ref": "main",
      "docsPath": "docs2"
    }
  },
  "nav": [
    {
      "label": "Coffee Guide",
      "items": [
        {
          "label": "Introduction",
          "path": "/"
        },
        {
          "label": "Roasting",
          "path": "/test-page"
        },
        {
          "label": "Equipment",
          "path": "/api-reference"
        }
      ]
    }
  ],
  "links": {
    "issues": "https://github.com/anomalyco/gittydocs/issues"
  }
}
