// This file is generated by prepare-docs.ts

export interface GitHubRepo {
  owner: string
  repo: string
  ref: string
  docsPath: string
}

export interface NavItem {
  label: string
  path?: string
  items?: NavItem[]
  accordion?: boolean
}

export interface DocsConfig {
  site: {
    name: string
    logo?: string
    repo?: GitHubRepo
  }
  nav?: NavItem[]
  links?: {
    issues?: string
  }
}

export const gittydocsConfig: DocsConfig | null = {
  "site": {
    "name": "gittydocs",
    "repo": {
      "owner": "anomalyco",
      "name": "gittydocs",
      "ref": "main",
      "docsPath": "docs"
    }
  },
  "nav": [
    {
      "label": "Getting Started",
      "items": [
        {
          "label": "Introduction",
          "path": "/"
        },
        {
          "label": "Getting Started",
          "path": "/getting-started"
        },
        {
          "label": "Configuration",
          "path": "/configuration"
        },
        {
          "label": "Documentation Structure",
          "path": "/structure"
        }
      ]
    },
    {
      "label": "Guides",
      "items": [
        {
          "label": "Quick Start",
          "path": "/guides/quickstart"
        }
      ]
    }
  ],
  "links": {
    "issues": "https://github.com/anomalyco/gittydocs/issues"
  }
}
